"""crear tabla tipo_programa

Revision ID: 1c03bcb27494
Revises: 
Create Date: 2026-04-18 21:49:14.068447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c03bcb27494'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_programa',
    sa.Column('idTipoPrograma', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idTipoPrograma')
    )
    op.create_index(op.f('ix_tipo_programa_idTipoPrograma'), 'tipo_programa', ['idTipoPrograma'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_programa_idTipoPrograma'), table_name='tipo_programa')
    op.drop_table('tipo_programa')
    # ### end Alembic commands ###
