"""cambiando las tablas a snake_case

Revision ID: 26bc2b8d2af9
Revises: 1c03bcb27494
Create Date: 2026-04-19 15:26:08.184590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bc2b8d2af9'
down_revision: Union[str, Sequence[str], None] = '1c03bcb27494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_programa', sa.Column('id_tipo_programa', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tipo_programa_idTipoPrograma'), table_name='tipo_programa')
    op.create_index(op.f('ix_tipo_programa_id_tipo_programa'), 'tipo_programa', ['id_tipo_programa'], unique=False)
    op.drop_column('tipo_programa', 'idTipoPrograma')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_programa', sa.Column('idTipoPrograma', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_tipo_programa_id_tipo_programa'), table_name='tipo_programa')
    op.create_index(op.f('ix_tipo_programa_idTipoPrograma'), 'tipo_programa', ['idTipoPrograma'], unique=False)
    op.drop_column('tipo_programa', 'id_tipo_programa')
    # ### end Alembic commands ###
