"""fix: recreando tabla tipo_programa

Revision ID: 08ccdffc578a
Revises: 
Create Date: 2026-04-20 10:51:32.436433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ccdffc578a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_programa',
    sa.Column('id_tipo_programa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_programa')
    )
    op.create_index(op.f('ix_tipo_programa_id_tipo_programa'), 'tipo_programa', ['id_tipo_programa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_programa_id_tipo_programa'), table_name='tipo_programa')
    op.drop_table('tipo_programa')
    # ### end Alembic commands ###
