"""feat: añadiendo created_at y updated_at a las tablas tipo y programa

Revision ID: 0ed11240d8d7
Revises: 083a5c4e844a
Create Date: 2026-04-22 10:17:42.964552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed11240d8d7'
down_revision: Union[str, Sequence[str], None] = '083a5c4e844a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programa', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('programa', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tipo_programa', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tipo_programa', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_programa', 'updated_at')
    op.drop_column('tipo_programa', 'created_at')
    op.drop_column('programa', 'updated_at')
    op.drop_column('programa', 'created_at')
    # ### end Alembic commands ###
