"""feat: agregar cupo_minimo a tipos_programa

Revision ID: 108d11c8fc35
Revises: 67944a20cf1c
Create Date: 2026-04-26 09:40:44.247587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108d11c8fc35'
down_revision: Union[str, Sequence[str], None] = '67944a20cf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_programa', sa.Column('cupo_minimo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_programa', 'cupo_minimo')
    # ### end Alembic commands ###
