"""feat: agregando tabla modalidad_academica

Revision ID: 18042aef8597
Revises: 5d576dcd852e
Create Date: 2026-04-23 16:50:13.813512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18042aef8597'
down_revision: Union[str, Sequence[str], None] = '5d576dcd852e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalidad_academica',
    sa.Column('id_modalidad_academica', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_modalidad', sa.String(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_modalidad_academica')
    )
    op.create_index(op.f('ix_modalidad_academica_id_modalidad_academica'), 'modalidad_academica', ['id_modalidad_academica'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modalidad_academica_id_modalidad_academica'), table_name='modalidad_academica')
    op.drop_table('modalidad_academica')
    # ### end Alembic commands ###
