"""feat: creando tablas alumno y detalle_programa_alumno

Revision ID: 2fbcbd44e1ca
Revises: 7d82fd3e1d03
Create Date: 2026-04-24 16:59:02.298975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbcbd44e1ca'
down_revision: Union[str, Sequence[str], None] = '7d82fd3e1d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_programa_alumno',
    sa.Column('id_detalle_programa_alumno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_programa_version_edicion', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_modalidad_academica', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_modalidad_academica'], ['modalidad_academica.id_modalidad_academica'], ),
    sa.ForeignKeyConstraint(['id_programa_version_edicion'], ['programa_version_edicion.id_programa_version_edicion'], ),
    sa.PrimaryKeyConstraint('id_detalle_programa_alumno')
    )
    op.create_index(op.f('ix_detalle_programa_alumno_id_detalle_programa_alumno'), 'detalle_programa_alumno', ['id_detalle_programa_alumno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_programa_alumno_id_detalle_programa_alumno'), table_name='detalle_programa_alumno')
    op.drop_table('detalle_programa_alumno')
    # ### end Alembic commands ###
