"""feat: añadiento tabla horario

Revision ID: 3070bb32c83d
Revises: e3ec9975595c
Create Date: 2026-04-24 10:33:24.504334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3070bb32c83d'
down_revision: Union[str, Sequence[str], None] = 'e3ec9975595c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_detalle_programa_modulo', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(), nullable=False),
    sa.Column('hora_ini', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_detalle_programa_modulo'], ['detalle_programa_modulo.id_detalle_programa_modulo'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index(op.f('ix_horario_id_horario'), 'horario', ['id_horario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horario_id_horario'), table_name='horario')
    op.drop_table('horario')
    # ### end Alembic commands ###
