"""feat: agregar campos orden y modalidad a detalle_programa_modulo

Revision ID: 549e6f3ac16b
Revises: a96b51b54d10
Create Date: 2026-04-26 13:12:30.234455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549e6f3ac16b'
down_revision: Union[str, Sequence[str], None] = 'a96b51b54d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_programa_modulo', sa.Column('id_modalidad', sa.Integer(), nullable=True))
    op.add_column('detalle_programa_modulo', sa.Column('orden', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'detalle_programa_modulo', 'modalidades', ['id_modalidad'], ['id_modalidad'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_programa_modulo', type_='foreignkey')
    op.drop_column('detalle_programa_modulo', 'orden')
    op.drop_column('detalle_programa_modulo', 'id_modalidad')
    # ### end Alembic commands ###
