"""feat: agregar tabla programa_version_edicion

Revision ID: 588a1a9bb449
Revises: ac25e6d82f8b
Create Date: 2026-04-24 08:08:33.146053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588a1a9bb449'
down_revision: Union[str, Sequence[str], None] = 'ac25e6d82f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programa_version_edicion',
    sa.Column('id_programa_version_edicion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_programa_version', sa.Integer(), nullable=False),
    sa.Column('id_modalidad', sa.Integer(), nullable=False),
    sa.Column('edicion', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.String(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('cupo_maximo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_modalidad'], ['modalidad.id_modalidad'], ),
    sa.ForeignKeyConstraint(['id_programa_version'], ['programa_version.id_programa_version'], ),
    sa.PrimaryKeyConstraint('id_programa_version_edicion')
    )
    op.create_index(op.f('ix_programa_version_edicion_id_programa_version_edicion'), 'programa_version_edicion', ['id_programa_version_edicion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programa_version_edicion_id_programa_version_edicion'), table_name='programa_version_edicion')
    op.drop_table('programa_version_edicion')
    # ### end Alembic commands ###
