"""feat: añadiendo tabla modulo

Revision ID: 5d576dcd852e
Revises: d2afd185cd34
Create Date: 2026-04-23 12:14:45.129465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d576dcd852e'
down_revision: Union[str, Sequence[str], None] = 'd2afd185cd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('id_modulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_programa_version', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('nombre_modulo', sa.String(), nullable=False),
    sa.Column('horas_academicas', sa.Integer(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_programa_version'], ['programa_version.id_programa_version'], ),
    sa.PrimaryKeyConstraint('id_modulo')
    )
    op.create_index(op.f('ix_modulo_id_modulo'), 'modulo', ['id_modulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modulo_id_modulo'), table_name='modulo')
    op.drop_table('modulo')
    # ### end Alembic commands ###
