"""feat: agregando tabla alumno

Revision ID: 7d82fd3e1d03
Revises: 3070bb32c83d
Create Date: 2026-04-24 16:34:24.977394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d82fd3e1d03'
down_revision: Union[str, Sequence[str], None] = '3070bb32c83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id_alumno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_alumno'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_alumno_id_alumno'), 'alumno', ['id_alumno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumno_id_alumno'), table_name='alumno')
    op.drop_table('alumno')
    # ### end Alembic commands ###
