"""feat: agregar tabla historial_modulo

Revision ID: 88cbe3578c57
Revises: d5424f1e1b40
Create Date: 2026-04-26 11:40:01.501513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cbe3578c57'
down_revision: Union[str, Sequence[str], None] = 'd5424f1e1b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_modulo',
    sa.Column('id_historial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_detalle_programa_modulo', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_detalle_programa_modulo'], ['detalle_programa_modulo.id_detalle_programa_modulo'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_modulo_id_historial'), 'historial_modulo', ['id_historial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_modulo_id_historial'), table_name='historial_modulo')
    op.drop_table('historial_modulo')
    # ### end Alembic commands ###
