"""feat: agregando campos de fecha original a tabla historial_modulo

Revision ID: a96b51b54d10
Revises: 88cbe3578c57
Create Date: 2026-04-26 11:50:13.744087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96b51b54d10'
down_revision: Union[str, Sequence[str], None] = '88cbe3578c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_modulo', sa.Column('fecha_inicio_original', sa.Date(), nullable=True))
    op.add_column('historial_modulo', sa.Column('fecha_fin_original', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial_modulo', 'fecha_fin_original')
    op.drop_column('historial_modulo', 'fecha_inicio_original')
    # ### end Alembic commands ###
