"""feat: añadiendo tabla modalidad

Revision ID: ac25e6d82f8b
Revises: 18042aef8597
Create Date: 2026-04-23 17:11:32.208643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac25e6d82f8b'
down_revision: Union[str, Sequence[str], None] = '18042aef8597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalidad',
    sa.Column('id_modalidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_modalidad')
    )
    op.create_index(op.f('ix_modalidad_id_modalidad'), 'modalidad', ['id_modalidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modalidad_id_modalidad'), table_name='modalidad')
    op.drop_table('modalidad')
    # ### end Alembic commands ###
