"""feat: añadiendo tabla de requisitos

Revision ID: b84bbaf6e7f1
Revises: 2fbcbd44e1ca
Create Date: 2026-04-24 17:11:25.451783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84bbaf6e7f1'
down_revision: Union[str, Sequence[str], None] = '2fbcbd44e1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisito',
    sa.Column('id_requisito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_modalidad_academica', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_modalidad_academica'], ['modalidad_academica.id_modalidad_academica'], ),
    sa.PrimaryKeyConstraint('id_requisito')
    )
    op.create_index(op.f('ix_requisito_id_requisito'), 'requisito', ['id_requisito'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisito_id_requisito'), table_name='requisito')
    op.drop_table('requisito')
    # ### end Alembic commands ###
