"""feat: agregando tabla programa_version

Revision ID: d2afd185cd34
Revises: 0ed11240d8d7
Create Date: 2026-04-22 10:23:19.189785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2afd185cd34'
down_revision: Union[str, Sequence[str], None] = '0ed11240d8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programa_version',
    sa.Column('id_programa_version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_programa', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_programa'], ['programa.id_programa'], ),
    sa.PrimaryKeyConstraint('id_programa_version')
    )
    op.create_index(op.f('ix_programa_version_id_programa_version'), 'programa_version', ['id_programa_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programa_version_id_programa_version'), table_name='programa_version')
    op.drop_table('programa_version')
    # ### end Alembic commands ###
