"""refactor: estandarizando tabla programa_version_edicion

Revision ID: d5424f1e1b40
Revises: 108d11c8fc35
Create Date: 2026-04-26 10:37:39.725951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5424f1e1b40'
down_revision: Union[str, Sequence[str], None] = '108d11c8fc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programa_version_edicion', sa.Column('estado', sa.String(length=20), nullable=False, server_default='programado'))
    op.add_column('programa_version_edicion', sa.Column('descripcion', sa.String(length=500), nullable=True))
    op.add_column('programa_version_edicion', sa.Column('precio', sa.Float(), nullable=True))
    op.drop_column('programa_version_edicion', 'vigente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programa_version_edicion', sa.Column('vigente', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('programa_version_edicion', 'precio')
    op.drop_column('programa_version_edicion', 'descripcion')
    op.drop_column('programa_version_edicion', 'estado')
    # ### end Alembic commands ###
