"""feat: agregar tabla detalle_programa_modulo

Revision ID: e3ec9975595c
Revises: f4ccaad408b6
Create Date: 2026-04-24 10:09:09.320884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ec9975595c'
down_revision: Union[str, Sequence[str], None] = 'f4ccaad408b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_programa_modulo',
    sa.Column('id_detalle_programa_modulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_programa_version_edicion', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_programa_version_edicion'], ['programa_version_edicion.id_programa_version_edicion'], ),
    sa.PrimaryKeyConstraint('id_detalle_programa_modulo')
    )
    op.create_index(op.f('ix_detalle_programa_modulo_id_detalle_programa_modulo'), 'detalle_programa_modulo', ['id_detalle_programa_modulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_programa_modulo_id_detalle_programa_modulo'), table_name='detalle_programa_modulo')
    op.drop_table('detalle_programa_modulo')
    # ### end Alembic commands ###
