"""feat: agregar tabla docente

Revision ID: f4ccaad408b6
Revises: 588a1a9bb449
Create Date: 2026-04-24 09:00:53.540272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ccaad408b6'
down_revision: Union[str, Sequence[str], None] = '588a1a9bb449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id_docente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_docente'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_docente_id_docente'), 'docente', ['id_docente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docente_id_docente'), table_name='docente')
    op.drop_table('docente')
    # ### end Alembic commands ###
