from models.tipo_programa import TipoPrograma
from models.programa import Programa
from models.programa_version import ProgramaVersion
from models.modulo import Modulo
from models.modalidad_academica import ModalidadAcademica
from models.modalidad import Modalidad
from models.programa_version_edicion import ProgramaVersionEdicion
from models.docente import Docente
from models.detalle_programa_modulo import DetalleProgramaModulo
from models.horario import Horario
from models.alumno import Alumno
from models.detalle_programa_alumno import DetalleProgramaAlumno
from models.requisito import Requisito
